routes/web.php
<?php
Auth::routes();
/* User Route Group */
Route::group(['prefix' => 'user', 'middleware' => ["checkUserAuth"]], function () {

    Route::post("addComment",'Site\ProductController@addComment')->name("comment.store");

    Route::get('/profile', 'Site\ProfileController@show')->name("userProfile");
    Route::put('/update', 'Site\ProfileController@updateUserInfo')->name("updateUserInfo");

    Route::resource('addresses', 'Site\UserAddressController');
    Route::resource('wish_list', 'Site\WishListController');
    Route::get('order/items/{id}','Site\OrderController@getItems')->name("orderItem");




    Route::resource('orders', 'Site\OrderController');
});

Route::post('myData','Admin\OrderController@getAll');
Route::post('orderItem','Admin\OrderController@getorderItems');

Route::post('like', 'Site\ProductController@like')->name("like");

Route::post('/user/addWishList', 'Site\WishListController@addWishList')->name('addWishList');

Route::group(['prefix' => 'cart'], function () {
    Route::post('/addToCart', 'Site\CartController@addToCart')->name('cart.addToCart');
    Route::post('/deleteFromCart', 'Site\CartController@delete')->name('cart.deleteFromCart');
    Route::post('/counter/{dir}', 'Site\CartController@counter')->name('cart.counter');
});


Route::get('orders/track', 'Site\OrderController@track')->name("orderTrack");



Route::get('compaire', 'Site\CompaireController@index')->name("compaire");

Route::post('addCompaire', 'Site\CompaireController@store')->name("addCompaireToList");

Route::post('removeFromCompaire', 'Site\CompaireController@destroy')->name("removeFromCompaire");

Route::post('getProductsByType', 'Site\CompaireController@getProductsByType')->name("getProductsByType");

Route::post('addCompaireToListFromProduct', 'Site\CompaireController@addCompaireToListFromProduct')->name("addCompaireToListFromProduct");



Route::get('search', 'Site\HomeController@search')->name("search");

$this->post('login', 'Auth\LoginController@myLogin')->name('phoneLogin');

/* Public Route Group */

Route::get('/', 'Site\HomeController@index')->name("home");
Route::get('/product/{id}', 'Site\ProductController@show')->name('singleProduct');
Route::get('/category/{id}', 'Site\CategoryController@show')->name('categoryProducts');
Route::get('/cart', 'Site\CartController@show')->name("cart");
Route::get('/payment', 'Site\PaymentController@pay')->name("pay");

/* Admin Route Group */

Route::group(['prefix' => 'dashboard909', 'middleware' => ['checkAdminAuth']], function () {


    Route::post('getTypes', 'Admin\ProductTypeController@getTypes')->name("getTypes");
    Route::post('getTypeFromOption', 'Admin\ProductOptionController@getTypeFromOption')->name("getTypeFromOption");

    /* Setting Routes */
    Route::group(['prefix' => 'settings'], function () {

        Route::resource('options', 'Admin\OptionController');
        Route::resource('cities', 'Admin\CityController');
        Route::resource('states', 'Admin\StateController');
        Route::resource('navs', 'Admin\NavController');
        Route::resource('payments', 'Admin\PaymentController');
        Route::resource('shoppings', 'Admin\ShoppingController');
        Route::resource('socials', 'Admin\SocialController');
    });
    Route::resource('productOptionCategories', 'Admin\ProductOptionCategoryController');
    Route::resource('productOptions', 'Admin\productOptionController');
    Route::resource('products', 'Admin\ProductController');
    Route::resource('brands', 'Admin\BrandController');
    Route::resource('offers', 'Admin\OfferController');
    Route::resource('shippings', 'Admin\ShippingController');
    Route::resource('categories', 'Admin\CategoryController');
    Route::resource('product_types', 'Admin\ProductTypeController');
    Route::resource('sliders', 'Admin\SliderController');
    Route::resource('features', 'Admin\FeatureController');
    Route::resource('feature_categories', 'Admin\FeatureCategoryController');
    Route::resource('banners', 'Admin\BannerController');
    Route::resource('comments', 'Admin\CommentController');
    Route::resource('companies', 'Admin\CompanyController');
    Route::resource('warranties', 'Admin\WarrantyController');
    Route::resource('users', 'Admin\UserController');
    Route::resource('admins', 'Admin\AdminController');
    Route::get('/', 'Admin\DashboardController@index')->name("dashboard");
    /* Media Routes */
    /* Admin Profile Routes */
    Route::get('logout/0', 'Auth\AdminAuthController@logout')->name("adminLogout");
    Route::get('/password', 'Admin\DashboardController@password')->name("password");
    Route::post('/password', 'Admin\DashboardController@passwordStore');
    Route::get('/avatar', 'Admin\DashboardController@avatar')->name("avatar");
    Route::post('/avatar', 'Admin\DashboardController@avatarStore');
    Route::get('/profile', 'Admin\DashboardController@profile')->name("profile");
    Route::post('/profile', 'Admin\DashboardController@profileStore');

    Route::resource('order', 'Admin\OrderController');
//    Route::resource('order', 'Admin\OrderController');
});

Route::prefix("dashboard909/media")->group(function () {
    Route::delete('{id}', 'Admin\MediaController@destroy')->name("media.destroy");
    Route::post('ajaxEdit/{id}', 'Admin\MediaController@update')->name("media.edit");
    Route::post('store', 'Admin\MediaController@store')->name("media.store");
    Route::get('/', 'Admin\MediaController@index')->name("media.index");
    Route::get('picker', 'Admin\MediaController@picker')->name("media.picker");
    Route::post('/ajaxSearch', 'Admin\MediaController@ajaxSearch')->name("media.search");
});

Route::group(['prefix' => 'dashboard909'], function () {
    /* Admin Auth */
    // Authentication Routes...
    Route::get('login', 'Auth\AdminAuthController@showLoginForm');
    Route::post('login', 'Auth\AdminAuthController@login')->name('adminLogin');
    Route::get('logout', 'Auth\AdminAuthController@logout')->name('adminLogout');
    // Password Reset Routes...
    Route::get('password/reset/{token?}', 'Auth\AdminPasswordController@showResetForm');
    Route::post('password/email', 'Auth\AdminPasswordController@sendResetLinkEmail');
    Route::post('password/reset', 'Auth\AdminResetPasswordController@reset');
});

app/Http/Controllers/Admin/CompanyController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;

use App\Model\Company;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies= Company::all();
        return view('panel.companies.index',compact('companies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("panel.companies.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|min:3|max:40',
            'media_id' => 'nullable|exists:media,id'
        ]);
        Company::create($request->all());
        Session::flash("ok","شرکت با موفقیت ایجاد شد");
        return redirect(route("companies.index"));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company=Company::with("media")->find($id);
        return view("panel.companies.edit",compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|min:3|max:40',
            'media_id' => 'nullable|exists:media,id'
        ]);
        Company::find($id)->update($request->all());
        Session::flash("ok","شرکت با موفقیت ایجاد شد");
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Company::find($id)->delete();
    }
}

resources/views/panel/companies/create.blade.php
@extends('panel.layout')
@section("title") ساخت شرکت @endsection
@section('content')


    <div class="row">
        <div class="col-md-12">

            <div class="portlet box blue-hoki">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-building"></i>افزودن شرکت </div>
                    <div class="tools">
                        <!--<a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                        <a href="#portlet-config" data-toggle="modal" class="config" data-original-title="" title=""> </a>
                        <a href="javascript:;" class="reload" data-original-title="" title=""> </a>
                        <a href="javascript:;" class="remove" data-original-title="" title=""> </a>-->
                    </div>
                </div>
                <div class="portlet-body">
                    @include("errors.list")
                </div>
                <div class="portlet-body form">
                    <!-- BEGIN FORM-->
                    {!! Form::open(["class"=>"form-horizontal","url"=>route("companies.store"),"method"=>"post"]) !!}

                    <div class="form-body">

                        <div class="form-group form-md-line-input">
                            {!! Form::label("name","نام شرکت",["class"=>"col-md-2 control-label"]) !!}
                            <div class="col-md-4">
                                {!! Form::input("text","name",null,["class"=>"form-control","placeholder"=>"نام شرکت"]) !!}
                                <div class="form-control-focus"> </div>
                            </div>
                        </div>

                    </div>
                    <div class="form-actions fluid">
                        <div class="row">
                            <div class="col-md-offset-3 col-md-9">
                                {!! Form::submit("ذخیره",["class"=>"btn green"]) !!}
                                <a href="{{route("companies.index")}}"><button type="button" class="btn default">بازگشت</button></a>
                            </div>
                        </div>
                    </div>
                {!! Form::close() !!}
                <!-- END FORM-->
                </div>
            </div>


        </div>
    </div>


@endsection

resources/views/panel/companies/edit.blade.php
@extends('panel.layout')
@section("title") ساخت شرکت @endsection
@section('content')


    <div class="row">
        <div class="col-md-12">

            <div class="portlet box blue-hoki">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-building"></i>ویرایش شرکت </div>
                    <div class="tools">
                        <!--<a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                        <a href="#portlet-config" data-toggle="modal" class="config" data-original-title="" title=""> </a>
                        <a href="javascript:;" class="reload" data-original-title="" title=""> </a>
                        <a href="javascript:;" class="remove" data-original-title="" title=""> </a>-->
                    </div>
                </div>
                <div class="portlet-body">
                    @include("errors.list")
                </div>
                <div class="portlet-body form">
                    <!-- BEGIN FORM-->
                    {!! Form::open(["class"=>"form-horizontal","url"=>route("companies.update",$company->id),"method"=>"put"]) !!}

                    <div class="form-body">

                        <div class="form-group form-md-line-input">
                            {!! Form::label("name","نام شرکت",["class"=>"col-md-2 control-label"]) !!}
                            <div class="col-md-4">
                                {!! Form::input("text","name",$company->name,["class"=>"form-control","placeholder"=>"نام شرکت"]) !!}
                                <div class="form-control-focus"> </div>
                            </div>
                        </div>
                        <hr>


                    </div>


                    <div class="form-actions fluid">
                        <div class="row">
                            <div class="col-md-offset-3 col-md-9">
                                {!! Form::submit("ویرایش",["class"=>"btn green"]) !!}
                                <a href="{{route("companies.index")}}"><button type="button" class="btn default">بازگشت</button></a>
                            </div>
                        </div>
                    </div>
                {!! Form::close() !!}
                <!-- END FORM-->
                </div>
            </div>


        </div>
    </div>


@endsection

resources/views/panel/companies/index.blade.php
@extends('panel.layout')

@section('content')

    <div class="row">
        <div class="col-md-12">

            <div class="portlet box blue-hoki">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-building"></i>لیست کمپانی ها
                    </div>
                    <div class="pull-left">
                        <a class="btn green" href="{{route('companies.create')}}"> <i class="fa fa-plus"></i>ایجاد کمپانی جدید</a>
                    </div>
                </div>
                <div class="portlet-body">
                    @include("errors.list")
                </div>
                <div class="portlet-body">
                    <!-- BEGIN TABLE-->
                    <table class="table table-striped table-bordered table-hover datatable" id="sample_1">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>نام کمپانی</th>
{{--                            <th>تصویر</th>--}}
                            <th>تاریخ</th>
                            <th>عملیات</th>
                        </tr>
                        </thead>


                        <tbody>
                        @foreach($companies as $company)

                            <tr>
                                <td>{{ $company->id }}</td>
                                <td>{{ $company->name }}</td>
{{--                                <td> {!!  thumb($company->media,1) !!}  </td>--}}
                                <td><span class='label label-primary'>ویرایش {{ jDate::forge($company->updated_at)->format('Y/m/d H:i:s') }}</span> <span class='label label-primary'>ساخت : {{ jDate::forge($company->created_at)->format('Y/m/d H:i:s') }}</span></td>
                                <td><div class="btn-group btn-group-lg" role="group"><a href="{{route('companies.edit', $company->id)}}" class="btn green">ویرایش</a></div><div class="btn-group btn-group-lg" role="group">

                                        {!! Form::open(['url'=>route('companies.destroy', $company->id),'method'=>'delete','class'=>'delete']) !!}
                                        <button type="submit" class="btn red"> حذف</button> {!! Form::close() !!} </div></td>
                            </tr>

                        @endforeach
                        </tbody>

                    </table>
                    <!-- END TABLE-->
                </div>
            </div>


        </div>
    </div>


@endsection