routes/web.php
<?php
Auth::routes();
/* User Route Group */
Route::group(['prefix' => 'user', 'middleware' => ["checkUserAuth"]], function () {

    Route::post("addComment",'Site\ProductController@addComment')->name("comment.store");

    Route::get('/profile', 'Site\ProfileController@show')->name("userProfile");
    Route::put('/update', 'Site\ProfileController@updateUserInfo')->name("updateUserInfo");

    Route::resource('addresses', 'Site\UserAddressController');
    Route::resource('wish_list', 'Site\WishListController');
    Route::get('order/items/{id}','Site\OrderController@getItems')->name("orderItem");




    Route::resource('orders', 'Site\OrderController');
});

Route::post('myData','Admin\OrderController@getAll');
Route::post('orderItem','Admin\OrderController@getorderItems');

Route::post('like', 'Site\ProductController@like')->name("like");

Route::post('/user/addWishList', 'Site\WishListController@addWishList')->name('addWishList');

Route::group(['prefix' => 'cart'], function () {
    Route::post('/addToCart', 'Site\CartController@addToCart')->name('cart.addToCart');
    Route::post('/deleteFromCart', 'Site\CartController@delete')->name('cart.deleteFromCart');
    Route::post('/counter/{dir}', 'Site\CartController@counter')->name('cart.counter');
});


Route::get('orders/track', 'Site\OrderController@track')->name("orderTrack");



Route::get('compaire', 'Site\CompaireController@index')->name("compaire");

Route::post('addCompaire', 'Site\CompaireController@store')->name("addCompaireToList");

Route::post('removeFromCompaire', 'Site\CompaireController@destroy')->name("removeFromCompaire");

Route::post('getProductsByType', 'Site\CompaireController@getProductsByType')->name("getProductsByType");

Route::post('addCompaireToListFromProduct', 'Site\CompaireController@addCompaireToListFromProduct')->name("addCompaireToListFromProduct");



Route::get('search', 'Site\HomeController@search')->name("search");

$this->post('login', 'Auth\LoginController@myLogin')->name('phoneLogin');

/* Public Route Group */

Route::get('/', 'Site\HomeController@index')->name("home");
Route::get('/product/{id}', 'Site\ProductController@show')->name('singleProduct');
Route::get('/category/{id}', 'Site\CategoryController@show')->name('categoryProducts');
Route::get('/cart', 'Site\CartController@show')->name("cart");
Route::get('/payment', 'Site\PaymentController@pay')->name("pay");

/* Admin Route Group */

Route::group(['prefix' => 'dashboard909', 'middleware' => ['checkAdminAuth']], function () {


    Route::post('getTypes', 'Admin\ProductTypeController@getTypes')->name("getTypes");
    Route::post('getTypeFromOption', 'Admin\ProductOptionController@getTypeFromOption')->name("getTypeFromOption");

    /* Setting Routes */
    Route::group(['prefix' => 'settings'], function () {

        Route::resource('options', 'Admin\OptionController');
        Route::resource('cities', 'Admin\CityController');
        Route::resource('states', 'Admin\StateController');
        Route::resource('navs', 'Admin\NavController');
        Route::resource('payments', 'Admin\PaymentController');
        Route::resource('shoppings', 'Admin\ShoppingController');
        Route::resource('socials', 'Admin\SocialController');
    });
    Route::resource('productOptionCategories', 'Admin\ProductOptionCategoryController');
    Route::resource('productOptions', 'Admin\productOptionController');
    Route::resource('products', 'Admin\ProductController');
    Route::resource('brands', 'Admin\BrandController');
    Route::resource('offers', 'Admin\OfferController');
    Route::resource('shippings', 'Admin\ShippingController');
    Route::resource('categories', 'Admin\CategoryController');
    Route::resource('product_types', 'Admin\ProductTypeController');
    Route::resource('sliders', 'Admin\SliderController');
    Route::resource('features', 'Admin\FeatureController');
    Route::resource('feature_categories', 'Admin\FeatureCategoryController');
    Route::resource('banners', 'Admin\BannerController');
    Route::resource('comments', 'Admin\CommentController');
    Route::resource('companies', 'Admin\CompanyController');
    Route::resource('warranties', 'Admin\WarrantyController');
    Route::resource('users', 'Admin\UserController');
    Route::resource('admins', 'Admin\AdminController');
    Route::get('/', 'Admin\DashboardController@index')->name("dashboard");
    /* Media Routes */
    /* Admin Profile Routes */
    Route::get('logout/0', 'Auth\AdminAuthController@logout')->name("adminLogout");
    Route::get('/password', 'Admin\DashboardController@password')->name("password");
    Route::post('/password', 'Admin\DashboardController@passwordStore');
    Route::get('/avatar', 'Admin\DashboardController@avatar')->name("avatar");
    Route::post('/avatar', 'Admin\DashboardController@avatarStore');
    Route::get('/profile', 'Admin\DashboardController@profile')->name("profile");
    Route::post('/profile', 'Admin\DashboardController@profileStore');

    Route::resource('order', 'Admin\OrderController');
//    Route::resource('order', 'Admin\OrderController');
});

Route::prefix("dashboard909/media")->group(function () {
    Route::delete('{id}', 'Admin\MediaController@destroy')->name("media.destroy");
    Route::post('ajaxEdit/{id}', 'Admin\MediaController@update')->name("media.edit");
    Route::post('store', 'Admin\MediaController@store')->name("media.store");
    Route::get('/', 'Admin\MediaController@index')->name("media.index");
    Route::get('picker', 'Admin\MediaController@picker')->name("media.picker");
    Route::post('/ajaxSearch', 'Admin\MediaController@ajaxSearch')->name("media.search");
});

Route::group(['prefix' => 'dashboard909'], function () {
    /* Admin Auth */
    // Authentication Routes...
    Route::get('login', 'Auth\AdminAuthController@showLoginForm');
    Route::post('login', 'Auth\AdminAuthController@login')->name('adminLogin');
    Route::get('logout', 'Auth\AdminAuthController@logout')->name('adminLogout');
    // Password Reset Routes...
    Route::get('password/reset/{token?}', 'Auth\AdminPasswordController@showResetForm');
    Route::post('password/email', 'Auth\AdminPasswordController@sendResetLinkEmail');
    Route::post('password/reset', 'Auth\AdminResetPasswordController@reset');
});

app/Http/Controllers/Admin/ProductOptionController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Model\ProductOption;
use App\Model\ProductOptionCategory;
use App\Http\Controllers\Controller;

class ProductOptionController extends Controller
{

    public function getTypeFromOption(Request $request){

        if(!$request->has("id")){
            abort(404);
        }

        $productOptionCategory = ProductOptionCategory::findorfail($request->id);

        return $productOptionCategory;

        if(!$productOptionCategory){
            abort(404);
        }


        return response(["type"=>$productOptionCategory->type]);

    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
//        dd("1");
        $productOptions = ProductOption::with('media')->with('productoptioncategory')->get();
//        dd($productOptions);
        return view('panel.productOptions.index', compact('productOptions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories=ProductOptionCategory::all()->pluck('name','id');
        return view('panel.ProductOptions.create',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
        ]);
        return $request;
        ProductOption::create($request->all());
        session()->flash("ok", "دشته بندی آپشن های محصولات با موفقیت ایجاد شد");
        return redirect(route("productOptions.index"));

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $ProductOptionCategories = ProductOptionCategory::pluck('name','id');

        $ProductOption = ProductOption::with('category')->findOrFail($id);

        $ProOpCat = $ProductOption->category;
//        return $ProOpCat->id ;
        return view('panel.productOptions.edit', compact('ProductOptionCategories','ProductOption','ProOpCat'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
//        return $request;
        ProductOption::find($id)->update($request->all());
        session()->flash('ok', "با موفقیت به روز رسانی شد");
        return redirect(route('productOptions.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        ProductOption::find($id)->delete();
        session()->flash('ok', "با موفقیت به حذف شد");
        return redirect(route('productOptions.index'));
    }
}

resources/views/panel/productOptions/create.blade.php
@extends('panel.layout')
@section("title") ساخت آپشن @endsection
@section('content')


    <div class="row">
        <div class="col-md-12">

            <div class="portlet box blue-hoki">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-building"></i>افزودن آپشن </div>
                    <div class="tools">
                        <!--<a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                        <a href="#portlet-config" data-toggle="modal" class="config" data-original-title="" title=""> </a>
                        <a href="javascript:;" class="reload" data-original-title="" title=""> </a>
                        <a href="javascript:;" class="remove" data-original-title="" title=""> </a>-->
                    </div>
                </div>
                <div class="portlet-body">
                    @include("errors.list")
                </div>
                <div class="portlet-body form">
                    <!-- BEGIN FORM-->
                    {!! Form::open(["class"=>"form-horizontal","url"=>route("productOptions.store"),"method"=>"post"]) !!}

                    <div class="form-body">
                        <div class="form-group form-md-line-input">
                            {!! Form::label("product_options_category_id","انتخاب دسته بندی",["class"=>"col-md-2 control-label"]) !!}
                            <div class="col-md-4">
                                {!! Form::select('product_option_category_id',$categories , 0,["class"=>"form-control selectRtl","id"=>"typeOption"]) !!}
                            </div>
                        </div>
                        <hr>
                        <div class="form-group form-md-line-input">
                            {!! Form::label("name","عنوان آپشن",["class"=>"col-md-2 control-label"]) !!}
                            <div class="col-md-4">
                                {!! Form::input("text","name",null,["class"=>"form-control","placeholder"=>"عنوان آپشن"]) !!}
                                <div class="form-control-focus"> </div>
                            </div>
                        </div>
                        <hr>

                        <div class="form-group form-md-line-input" id="type1">
                            {!! Form::label("name","انتخاب رنگ",["class"=>"col-md-2 control-label"]) !!}
                            <div class="col-md-4">

                                {!! Form::input("text","value","",["class"=>"form-control","placeholder"=>"انتخاب رنگ",'id'=>'mycp']) !!}
                                <div class="form-control-focus"> </div>
                            </div>
                        </div>
                        <div class="form-group form-md-line-input" id="type3">
                            {!! Form::label("name","محتوا",["class"=>"col-md-2 control-label"]) !!}
                            <div class="col-md-4">

                                {!! Form::input("text","value","",["class"=>"form-control","placeholder"=>"محتوا"]) !!}
                                <div class="form-control-focus"> </div>
                            </div>
                        </div>
                        <hr>
                        <div class="form-group form-md-line-input" id="type2">
                            <div class="col-md-8 col-md-offset-2">


                                <div class="row">
                                    <div class="col-md-3">

                                        <button type="button" data-action="thumb" class="galleryPickeraBtn btn btn-info"
                                                style="width:100%">انتخاب فایل چند رسانه ای برای دسته بندی
                                        </button>

                                    </div>

                                    <div class="col-md-3">

                                        {!! Form::text("image_name",null,['class'=>'form-control galleryInput','readonly'=>'readonly']) !!}
                                        <input class="imageHiddenInput" type="hidden" name="media_id" value="">

                                    </div>

                                    <div class="col-md-3">
                                        <figure class="preview" style="max-width:100%">

                                        </figure>
                                    </div>
                                </div>


                            </div>
                        </div>


                        <hr>

                    </div>


                    <div class="form-actions fluid">
                        <div class="row">
                            <div class="col-md-offset-3 col-md-9">
                                {!! Form::submit("ذخیره",["class"=>"btn green"]) !!}
                                <a href="{{route("productOptions.index")}}"><button type="button" class="btn default">بازگشت</button></a>
                            </div>
                        </div>
                    </div>
                {!! Form::close() !!}
                <!-- END FORM-->
                </div>
            </div>


        </div>
    </div>


@endsection


@section("extra_script")


    <script>

        $("#type1,#type3").hide();

        $("#typeOption").change(function(e){

            var pid = $(this).val();

            $.ajax({
                url     : '/dashboard909/getTypeFromOption',
                method  : 'post',
                data    : {id:pid},
                success : function(data){
                    $("#type1,#type2,#type3").hide(100,function(){
                        $("#type"+data.type).show(100);
                    });
                }
            });

        });

    </script>


@endsection

resources/views/panel/productOptions/edit.blade.php
@extends('panel.layout')
@section("title") ویرایش آپشن @endsection
@section('content')


    <div class="row">
        <div class="col-md-12">

            <div class="portlet box blue-hoki">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-building"></i>ویرایش آپشن
                    </div>
                    <div class="tools">
                        <!--<a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                        <a href="#portlet-config" data-toggle="modal" class="config" data-original-title="" title=""> </a>
                        <a href="javascript:;" class="reload" data-original-title="" title=""> </a>
                        <a href="javascript:;" class="remove" data-original-title="" title=""> </a>-->
                    </div>
                </div>
                <div class="portlet-body">
                    @include("errors.list")
                </div>
                <div class="portlet-body form">
                    <!-- BEGIN FORM-->
                    {!! Form::open(["class"=>"form-horizontal","url"=>route("productOptions.update",$ProductOption->id),"method"=>"patch"]) !!}
                    <div class="form-body">
                        <div class="form-group form-md-line-input">
                            {!! Form::label("product_options_category_id","عنوان دسته بندی",["class"=>"col-md-2 control-label"]) !!}
                            <div class="col-md-4">
                                {{--{!! Form::select('product_option_categories',$ProductOptionCategories,[$ProOpCat->id],["class"=>"col-md-2 control-label"]) !!}--}}

                                {!! Form::select("product_options_category_id",$ProductOptionCategories,[$ProOpCat->id],["class"=>"form-control "]) !!}


                                {{--{!! Form::label("product_options_category_id",$ProductOption->category->name,["class"=>"col-md-2 control-label"]) !!}--}}
                                {{--{!! Form::input("hidden","product_options_category_id",$ProductOption->category->id,["class"=>"form-control","placeholder"=>$ProductOption->category->name])  !!}--}}
                            </div>
                        </div>
                        <hr>
                        <div class="form-group form-md-line-input">
                            {!! Form::label("name","نام آپشن",["class"=>"col-md-2 control-label"]) !!}
                            <div class="col-md-4">
                                {!! Form::input("text","name",$ProductOption->name,["class"=>"form-control","placeholder"=>"نام آپشن"]) !!}
                                <div class="form-control-focus"></div>
                            </div>
                        </div>
                        @if($ProductOption->category->type == 1)
                        <hr>
                        <div class="form-group form-md-line-input">
                            {!! Form::label("name","انتخاب رنگ",["class"=>"col-md-2 control-label"]) !!}
                            <div class="col-md-4">
                                {!! Form::input("text","value","$ProductOption->value",["class"=>"form-control","placeholder"=>"انتخاب رنگ",'id'=>'mycp']) !!}
                                <div class="form-control-focus"></div>
                            </div>
                        </div>
                        @elseif($ProductOption->category->type == 3)
                        <hr>
                        <div class="form-group form-md-line-input">
                            {!! Form::label("name","محتوا",["class"=>"col-md-2 control-label"]) !!}
                            <div class="col-md-4">

                                {!! Form::input("text","value","",["class"=>"form-control","placeholder"=>"محتوا"]) !!}
                                <div class="form-control-focus"></div>
                            </div>
                        </div>
                        @elseif($ProductOption->category->type == 2)
                        <hr>
                        <div class="row">
                            <div class="col-md-4">

                                <button type="button" data-action="thumb" class="galleryPickeraBtn btn btn-info"
                                        style="width:100%">انتخاب تصویر آپشن
                                </button>

                            </div>

                            <div class="col-md-4">

                                @if(!is_null($ProductOption->media))

                                    {!! Form::text("image_name",$ProductOption->media->name,['class'=>'form-control galleryInput','readonly'=>'readonly']) !!}
                                    <input class="imageHiddenInput" type="hidden" name="media_id"
                                           value="{{$ProductOption->media->id}}">

                                @else

                                    {!! Form::text("image_name",null,['class'=>'form-control galleryInput','readonly'=>'readonly']) !!}
                                    <input class="imageHiddenInput" type="hidden" name="media_id">

                                @endif
                            </div>
                            <div class="col-md-2">
                                <figure class="preview" style="max-width:100%">

                                    {!! thumb($ProductOption->media) !!}

                                </figure>
                            </div>
                        </div>
                        @endif
                        <hr>
                    </div>
                    <div class="form-actions fluid">
                        <div class="row">
                            <div class="col-md-offset-3 col-md-9">
                                {!! Form::submit("ذخیره",["class"=>"btn green"]) !!}
                                <a href="{{route("productOptions.index")}}">
                                    <button type="button" class="btn default">بازگشت</button>
                                </a>
                            </div>
                        </div>
                    </div>
                {!! Form::close() !!}
                <!-- END FORM-->
                </div>
            </div>


        </div>
    </div>


@endsection

resources/views/panel/productOptions/index.blade.php
@extends('panel.layout')

@section('content')

    <div class="row">
        <div class="col-md-12">

            <div class="portlet box blue-hoki">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-building"></i>لیست آپشن ها
                    </div>
                    <div class="pull-left">
                        <a class="btn green" href="{{route('productOptions.create')}}"> <i class="fa fa-plus"></i>افزودن آپشن </a>
                    </div>
                </div>
                <div class="portlet-body">
                    @include("errors.list")
                </div>
                <div class="portlet-body">
                    <!-- BEGIN TABLE-->
                    <table class="table table-striped table-bordered table-hover datatable" id="sample_1">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>عنوان آپشن</th>
                            <th>نوع</th>
                            <th>دسته بندی</th>
                            <th>تصویر - مقدار</th>
                            <th>تاریخ</th>
                            <th>عملیات</th>
                        </tr>
                        </thead>
                        <tbody>


<!--                        --><?php //dd($productOptions);?>
                        @foreach($productOptions as $option)

                            <tr>
                                <td>{{ $option->id }}</td>
                                <td>{{ $option->name }}</td>
                                <td>{!! prdOptionType($option->productoptioncategory->type ) !!} </td>
                                <td>{{ $option->productoptioncategory->name}}</td>
                                <td> @if(isset($option->media)){!!  thumb($option->media,1) !!} @else @if($option->productoptioncategory->type == 1) <span style="padding: 0px 10px; margin-top: 40px !important;border-radius: 50%; background-color: {{$option->value}}"></span> @else {{$option->value}} @endif @endif  </td>
                                <td><span class='label label-primary'>ویرایش {{ jDate::forge($option->updated_at)->format('Y/m/d H:i:s') }}</span> <span class='label label-primary'>ساخت : {{ jDate::forge($option->created_at)->format('Y/m/d H:i:s') }}</span></td>
                                <td><div class="btn-group btn-group-lg" role="group"><a href="{{route('productOptions.edit', $option->id)}}" class="btn green">ویرایش</a></div><div class="btn-group btn-group-lg" role="group">
                                        {!! Form::open(['url'=>route('productOptions.destroy', $option->id),'method'=>'delete','class'=>'delete']) !!}
                                        <button type="submit" class="btn red"> حذف</button> {!! Form::close() !!} </div></td>
                            </tr>

                        @endforeach
                        </tbody>

                    </table>
                    <!-- END TABLE-->
                </div>
            </div>


        </div>
    </div>


@endsection