routes/web.php
<?php
Auth::routes();
/* User Route Group */
Route::group(['prefix' => 'user', 'middleware' => ["checkUserAuth"]], function () {

    Route::post("addComment",'Site\ProductController@addComment')->name("comment.store");

    Route::get('/profile', 'Site\ProfileController@show')->name("userProfile");
    Route::put('/update', 'Site\ProfileController@updateUserInfo')->name("updateUserInfo");

    Route::resource('addresses', 'Site\UserAddressController');
    Route::resource('wish_list', 'Site\WishListController');
    Route::get('order/items/{id}','Site\OrderController@getItems')->name("orderItem");




    Route::resource('orders', 'Site\OrderController');
});

Route::post('myData','Admin\OrderController@getAll');
Route::post('orderItem','Admin\OrderController@getorderItems');

Route::post('like', 'Site\ProductController@like')->name("like");

Route::post('/user/addWishList', 'Site\WishListController@addWishList')->name('addWishList');

Route::group(['prefix' => 'cart'], function () {
    Route::post('/addToCart', 'Site\CartController@addToCart')->name('cart.addToCart');
    Route::post('/deleteFromCart', 'Site\CartController@delete')->name('cart.deleteFromCart');
    Route::post('/counter/{dir}', 'Site\CartController@counter')->name('cart.counter');
});


Route::get('orders/track', 'Site\OrderController@track')->name("orderTrack");



Route::get('compaire', 'Site\CompaireController@index')->name("compaire");

Route::post('addCompaire', 'Site\CompaireController@store')->name("addCompaireToList");

Route::post('removeFromCompaire', 'Site\CompaireController@destroy')->name("removeFromCompaire");

Route::post('getProductsByType', 'Site\CompaireController@getProductsByType')->name("getProductsByType");

Route::post('addCompaireToListFromProduct', 'Site\CompaireController@addCompaireToListFromProduct')->name("addCompaireToListFromProduct");



Route::get('search', 'Site\HomeController@search')->name("search");

$this->post('login', 'Auth\LoginController@myLogin')->name('phoneLogin');

/* Public Route Group */

Route::get('/', 'Site\HomeController@index')->name("home");
Route::get('/product/{id}', 'Site\ProductController@show')->name('singleProduct');
Route::get('/category/{id}', 'Site\CategoryController@show')->name('categoryProducts');
Route::get('/cart', 'Site\CartController@show')->name("cart");
Route::get('/payment', 'Site\PaymentController@pay')->name("pay");

/* Admin Route Group */

Route::group(['prefix' => 'dashboard909', 'middleware' => ['checkAdminAuth']], function () {


    Route::post('getTypes', 'Admin\ProductTypeController@getTypes')->name("getTypes");
    Route::post('getTypeFromOption', 'Admin\ProductOptionController@getTypeFromOption')->name("getTypeFromOption");

    /* Setting Routes */
    Route::group(['prefix' => 'settings'], function () {

        Route::resource('options', 'Admin\OptionController');
        Route::resource('cities', 'Admin\CityController');
        Route::resource('states', 'Admin\StateController');
        Route::resource('navs', 'Admin\NavController');
        Route::resource('payments', 'Admin\PaymentController');
        Route::resource('shoppings', 'Admin\ShoppingController');
        Route::resource('socials', 'Admin\SocialController');
    });
    Route::resource('productOptionCategories', 'Admin\ProductOptionCategoryController');
    Route::resource('productOptions', 'Admin\productOptionController');
    Route::resource('products', 'Admin\ProductController');
    Route::resource('brands', 'Admin\BrandController');
    Route::resource('offers', 'Admin\OfferController');
    Route::resource('shippings', 'Admin\ShippingController');
    Route::resource('categories', 'Admin\CategoryController');
    Route::resource('product_types', 'Admin\ProductTypeController');
    Route::resource('sliders', 'Admin\SliderController');
    Route::resource('features', 'Admin\FeatureController');
    Route::resource('feature_categories', 'Admin\FeatureCategoryController');
    Route::resource('banners', 'Admin\BannerController');
    Route::resource('comments', 'Admin\CommentController');
    Route::resource('companies', 'Admin\CompanyController');
    Route::resource('warranties', 'Admin\WarrantyController');
    Route::resource('users', 'Admin\UserController');
    Route::resource('admins', 'Admin\AdminController');
    Route::get('/', 'Admin\DashboardController@index')->name("dashboard");
    /* Media Routes */
    /* Admin Profile Routes */
    Route::get('logout/0', 'Auth\AdminAuthController@logout')->name("adminLogout");
    Route::get('/password', 'Admin\DashboardController@password')->name("password");
    Route::post('/password', 'Admin\DashboardController@passwordStore');
    Route::get('/avatar', 'Admin\DashboardController@avatar')->name("avatar");
    Route::post('/avatar', 'Admin\DashboardController@avatarStore');
    Route::get('/profile', 'Admin\DashboardController@profile')->name("profile");
    Route::post('/profile', 'Admin\DashboardController@profileStore');

    Route::resource('order', 'Admin\OrderController');
//    Route::resource('order', 'Admin\OrderController');
});

Route::prefix("dashboard909/media")->group(function () {
    Route::delete('{id}', 'Admin\MediaController@destroy')->name("media.destroy");
    Route::post('ajaxEdit/{id}', 'Admin\MediaController@update')->name("media.edit");
    Route::post('store', 'Admin\MediaController@store')->name("media.store");
    Route::get('/', 'Admin\MediaController@index')->name("media.index");
    Route::get('picker', 'Admin\MediaController@picker')->name("media.picker");
    Route::post('/ajaxSearch', 'Admin\MediaController@ajaxSearch')->name("media.search");
});

Route::group(['prefix' => 'dashboard909'], function () {
    /* Admin Auth */
    // Authentication Routes...
    Route::get('login', 'Auth\AdminAuthController@showLoginForm');
    Route::post('login', 'Auth\AdminAuthController@login')->name('adminLogin');
    Route::get('logout', 'Auth\AdminAuthController@logout')->name('adminLogout');
    // Password Reset Routes...
    Route::get('password/reset/{token?}', 'Auth\AdminPasswordController@showResetForm');
    Route::post('password/email', 'Auth\AdminPasswordController@sendResetLinkEmail');
    Route::post('password/reset', 'Auth\AdminResetPasswordController@reset');
});

app/Http/Controllers/Admin/SliderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Model\Slider;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Session;

class SliderController extends Controller
{
    public function index()
    {
        $sliders = Slider::all();
        return view('panel.sliders.index', compact('sliders'));
    }

    public function create()
    {
        return view("panel.sliders.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'media_id' => 'nullable|exists:media,id'
        ]);
        if (!isset($request->status))
            $request->request->add(['status' => 0]);

        Slider::create($request->all());
        Session::flash("ok", "اسلایدر با موفقیت ایجاد شد");
        return redirect(route("sliders.index"));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $slider = Slider::with("media")->find($id);
        return view("panel.sliders.edit", compact('slider'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title' => 'required',
            'media_id' => 'nullable|exists:media,id'
        ]);
        Slider::find($id)->update($request->all());
        Session::flash("ok", "اسلایدر با موفقیت بروزسانی شد");
        return redirect(route('sliders.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Slider::find($id)->delete();
    }

}

resources/views/panel/sliders/create.blade.php
@extends('panel.layout')
@section("title") ساخت اسلایدر @endsection
@section('content')


    <div class="row">
        <div class="col-md-12">

            <div class="portlet box blue-hoki">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-building"></i>افزودن اسلایدر
                    </div>
                    <div class="tools">
                        <!--<a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                        <a href="#portlet-config" data-toggle="modal" class="config" data-original-title="" title=""> </a>
                        <a href="javascript:;" class="reload" data-original-title="" title=""> </a>
                        <a href="javascript:;" class="remove" data-original-title="" title=""> </a>-->
                    </div>
                </div>
                <div class="portlet-body">
                    @include("errors.list")
                </div>
                <div class="portlet-body form">
                    <!-- BEGIN FORM-->
                    {!! Form::open(["class"=>"form-horizontal","url"=>route("sliders.store"),"method"=>"post"]) !!}

                    <div class="form-body">

                        <div class="form-group form-md-line-input">
                            {!! Form::label("title","نام اسلایدر",["class"=>"col-md-2 control-label"]) !!}
                            <div class="col-md-4">
                                {!! Form::input("text","title",null,["class"=>"form-control","placeholder"=>"نام اسلایدر"]) !!}
                                <div class="form-control-focus"></div>
                            </div>
                        </div>
                        <hr>
                        <div class="form-group form-md-line-input">
                            {!! Form::label("body","متن اسلایدر",["class"=>"col-md-2 control-label"]) !!}
                            <div class="col-md-4">
                                {!! Form::input("text","body",null,["class"=>"form-control","placeholder"=>"متن اسلایدر"]) !!}
                                <div class="form-control-focus"></div>
                            </div>
                        </div>
                        <hr>
                        <div class="form-group form-md-line-input">
                            {!! Form::label("link","لینک اسلایدر",["class"=>"col-md-2 control-label"]) !!}
                            <div class="col-md-4">
                                {!! Form::input("text","link",null,["class"=>"form-control","placeholder"=>"لینک اسلایدر"]) !!}
                                <div class="form-control-focus"></div>
                            </div>
                        </div>

                        <hr>

                        <div class="row">
                            <div class="col-md-8 col-md-offset-2">
                                <div class="row">
                                    <div class="col-md-4">

                                        <button type="button" data-action="thumb" class="galleryPickeraBtn btn btn-info"
                                                style="width:100%">انتخاب تصویر اسلایدر
                                        </button>

                                    </div>

                                    <div class="col-md-4">

                                        {!! Form::text("image_name",null,['class'=>'form-control galleryInput','readonly'=>'readonly']) !!}
                                        <input class="imageHiddenInput" type="hidden" name="media_id" value="NULL">

                                    </div>

                                    <div class="col-md-2">
                                        <figure class="preview" style="max-width:100%">
                                            <img src="" class="img-responsive thumb">
                                        </figure>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <hr>

                        <div class="form-group form-md-line-input">
                            {!! Form::label("status","وضعیت انتشار",["class"=>"col-md-2 control-label"]) !!}
                            <div class="col-md-4">
                                <div class="md-checkbox">
                                    <input id="status" value="1" class="md-check" name="status" type="checkbox">
                                    <label for="status">
                                        <span></span>
                                        <span class="check"></span>
                                        <span class="box"></span> وضعیت انتشار </label>
                                </div>
                            </div>
                        </div>


                        <hr>

                    </div>


                    <div class="form-actions fluid">
                        <div class="row">
                            <div class="col-md-offset-3 col-md-9">
                                {!! Form::submit("ذخیره",["class"=>"btn green"]) !!}
                                <a href="{{route("sliders.index")}}">
                                    <button type="button" class="btn default">بازگشت</button>
                                </a>
                            </div>
                        </div>
                    </div>
                {!! Form::close() !!}
                <!-- END FORM-->
                </div>
            </div>


        </div>
    </div>


@endsection

resources/views/panel/sliders/edit.blade.php
@extends('panel.layout')
@section("title") ساخت اسلایدر @endsection
@section('content')


    <div class="row">
        <div class="col-md-12">

            <div class="portlet box blue-hoki">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-building"></i>افزودن اسلایدر
                    </div>
                    <div class="tools">
                        <!--<a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
                        <a href="#portlet-config" data-toggle="modal" class="config" data-original-title="" title=""> </a>
                        <a href="javascript:;" class="reload" data-original-title="" title=""> </a>
                        <a href="javascript:;" class="remove" data-original-title="" title=""> </a>-->
                    </div>
                </div>
                <div class="portlet-body">
                    @include("errors.list")
                </div>
                <div class="portlet-body form">
                    <!-- BEGIN FORM-->
                    {!! Form::open(["class"=>"form-horizontal","url"=>route("sliders.update",$slider->id),"method"=>"put"]) !!}

                    <div class="form-body">

                        <div class="form-group form-md-line-input">
                            {!! Form::label("title","نام اسلایدر",["class"=>"col-md-2 control-label"]) !!}
                            <div class="col-md-4">
                                {!! Form::input("text","title",$slider->title,["class"=>"form-control","placeholder"=>"نام اسلایدر"]) !!}
                                <div class="form-control-focus"></div>
                            </div>
                        </div>
                        <hr>
                        <div class="form-group form-md-line-input">
                            {!! Form::label("body","متن اسلایدر",["class"=>"col-md-2 control-label"]) !!}
                            <div class="col-md-4">
                                {!! Form::input("text","body",$slider->body,["class"=>"form-control","placeholder"=>"متن اسلایدر"]) !!}
                                <div class="form-control-focus"></div>
                            </div>
                        </div>
                        <hr>
                        <div class="form-group form-md-line-input">
                            {!! Form::label("link","لینک اسلایدر",["class"=>"col-md-2 control-label"]) !!}
                            <div class="col-md-4">
                                {!! Form::input("text","link",$slider->link,["class"=>"form-control","placeholder"=>"لینک اسلایدر"]) !!}
                                <div class="form-control-focus"></div>
                            </div>
                        </div>

                        <hr>

                        <div class="row">
                            <div class="col-md-8 col-md-offset-2">
                                <div class="row">
                                    <div class="col-md-4">

                                        <button type="button" data-action="thumb" class="galleryPickeraBtn btn btn-info"
                                                style="width:100%">انتخاب تصویر اسلایدر
                                        </button>

                                    </div>

                                    <div class="col-md-4">

                                        {!! Form::text("image_name",$slider->media->name,['class'=>'form-control galleryInput','readonly'=>'readonly']) !!}
                                        <input class="imageHiddenInput" type="hidden" name="media_id" value="NULL">

                                    </div>

                                    <div class="col-md-2">
                                        <figure class="preview" style="max-width:100%">
                                            <img src="" class="img-responsive thumb">
                                        </figure>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <hr>

                        <div class="form-group form-md-line-input">
                            {!! Form::label("status","وضعیت انتشار",["class"=>"col-md-2 control-label"]) !!}
                            <div class="col-md-4">
                                <div class="md-checkbox">
                                    <input id="status" value="1" class="md-check" {{$slider->status == 1 ? 'checked="checked"' : ""}} name="status" type="checkbox">
                                    <label for="status">
                                        <span></span>
                                        <span class="check"></span>
                                        <span class="box"></span> وضعیت انتشار </label>
                                </div>
                            </div>
                        </div>


                        <hr>

                    </div>


                    <div class="form-actions fluid">
                        <div class="row">
                            <div class="col-md-offset-3 col-md-9">
                                {!! Form::submit("ذخیره",["class"=>"btn green"]) !!}
                                <a href="{{route("sliders.index")}}">
                                    <button type="button" class="btn default">بازگشت</button>
                                </a>
                            </div>
                        </div>
                    </div>
                {!! Form::close() !!}
                <!-- END FORM-->
                </div>
            </div>


        </div>
    </div>


@endsection

resources/views/panel/sliders/index.blade.php
@extends('panel.layout')

@section('content')

    <div class="row">
        <div class="col-md-12">

            <div class="portlet box blue-hoki">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-building"></i>لیست اسلایدر ها
                    </div>
                    <div class="pull-left">
                        <a class="btn green" href="{{route('sliders.create')}}"> <i class="fa fa-plus"></i>اسلایدر جدید</a>
                    </div>
                </div>
                <div class="portlet-body">
                    @include("errors.list")
                </div>
                <div class="portlet-body">
                    <!-- BEGIN TABLE-->
                    <table class="table table-striped table-bordered table-hover datatable" id="sample_1">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>عنوان اسلایدر</th>
                            <th>تصویر</th>
                            <th>تاریخ</th>
                            <th>لینک اسلایدر</th>
                            <th>عملیات</th>
                        </tr>
                        </thead>


                        <tbody>
                        @foreach($sliders as $slider)

                            <tr>
                                <td>{{ $slider->id }}</td>
                                <td>{{ $slider->title }}</td>
                                <td> {!!  thumb($slider->media,1) !!}  </td>
                                <td>
                                    <span class='label label-primary'>ویرایش {{ jDate::forge($slider->updated_at)->format('Y/m/d H:i:s') }}</span>
                                    <span class='label label-primary'>ساخت : {{ jDate::forge($slider->created_at)->format('Y/m/d H:i:s') }}</span>
                                </td>
                                <td>
                                    <a target="_blank" href="{{ $slider->link }}"><span class='label label-primary'> کلیک کنید </span></a>
                                </td>
                                <td>
                                    <div class="btn-group btn-group-lg" role="group"><a
                                                href="{{route('sliders.edit', $slider->id)}}" class="btn green">ویرایش</a>
                                    </div>
                                    <div class="btn-group btn-group-lg" role="group">

                                        {!! Form::open(['url'=>route('sliders.destroy', $slider->id),'method'=>'delete','class'=>'delete']) !!}
                                        <button type="submit" class="btn red"> حذف</button> {!! Form::close() !!} </div>
                                </td>
                            </tr>

                        @endforeach
                        </tbody>

                    </table>
                    <!-- END TABLE-->
                </div>
            </div>


        </div>
    </div>


@endsection